import { Scientist } from './types.ts';

export const CHAPTERS_BY_GRADE = {
  6: [
    "The Wonderful World of Science",
    "Diversity in the Living World",
    "Mindful Eating: A Path to a Healthy Body",
    "Exploring Magnets",
    "Measurement of Length and Motion",
    "Materials Around Us",
    "Temperature and its Measurement",
    "A Journey through States of Water",
    "Methods of Separation in Everyday Life",
    "Living Creatures: Exploring their Characteristics",
    "Nature’s Treasures",
    "Beyond Earth",
  ],
  7: [
    "The Ever-Evolving World of Science",
    "Exploring Substances: Acidic, Basic, and Neutral",
    "Electricity: Circuits and their Components",
    "The World of Metals and Non-metals",
    "Changes Around Us: Physical and Chemical",
    "Adolescence: A Stage of Growth and Change",
    "Heat Transfer in Nature",
    "Measurement of Time and Motion",
    "Life Processes in Animals",
    "Life Processes in Plants",
    "Light: Shadows and Reflections",
    "Earth, Moon, and the Sun",
  ],
  8: [
    "Exploring the Investigative World of Science",
    "The Invisible Living World: Beyond Our Naked Eye",
    "Health: The Ultimate Treasure",
    "Electricity: Magnetic and Heating Effects",
    "Exploring Forces",
    "Pressure, Winds, Storms, and Cyclones",
    "Particulate Nature of Matter",
    "Nature of Matter: Elements, Compounds, and Mixtures",
    "The Amazing World of Solutes, Solvents, and Solutions",
    "Light: Mirrors and Lenses",
    "Keeping Time with the Skies",
    "How Nature Works in Harmony",
    "Our Home: Earth, a Unique Life Sustaining Planet",
  ],
  9: [
    "MATTER IN OUR SURROUNDINGS",
    "IS MATTER AROUND US PURE?",
    "ATOMS AND MOLECULES",
    "STRUCTURE OF THE ATOM",
    "THE FUNDAMENTAL UNIT OF LIFE",
    "TISSUES",
    "MOTION",
    "FORCE AND LAWS OF MOTION",
    "GRAVITATION",
    "WORK AND ENERGY",
    "SOUND",
    "IMPROVEMENT IN FOOD RESOURCES",
  ],
  10: [
    "Chemical Reactions and Equations",
    "Acids, Bases and Salts",
    "Metals and Non-metals",
    "Carbon and its Compounds",
    "Life Processes",
    "Control and Coordination",
    "How do Organisms Reproduce?",
    "Heredity",
    "Light – Reflection and Refraction",
    "The Human Eye and the Colourful World",
    "Electricity",
    "Magnetic Effects of Electric Current",
    "Our Environment",
  ],
};

export const SCIENTISTS: Scientist[] = [
  { name: 'Albert Einstein', field: 'Theoretical Physicist', description: 'Developed the theory of relativity, one of the two pillars of modern physics.' },
  { name: 'Marie Curie', field: 'Physicist and Chemist', description: 'Conducted pioneering research on radioactivity and was the first woman to win a Nobel Prize.' },
  { name: 'Isaac Newton', field: 'Mathematician & Physicist', description: 'Formulated the laws of motion and universal gravitation, which dominated scientists\' view of the physical universe for three centuries.' },
  { name: 'Charles Darwin', field: 'Naturalist & Biologist', description: 'Best known for his contributions to the science of evolution and the theory of natural selection.' },
  { name: 'Galileo Galilei', field: 'Astronomer & Physicist', description: 'The "father of observational astronomy," he made major improvements to the telescope and supported Copernicanism.' },
  { name: 'C. V. Raman', field: 'Physicist', description: 'Won the Nobel Prize for his work on light scattering and for the discovery of the effect named after him.' },
];